# Generated by Django 4.1 on 2022-09-14 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='Text',
            new_name='text',
        ),
    ]
